trigger:
  branches:
    include:
    - main
pool:
  vmImage: ubuntu-latest

variables:
  workingDirectory: '$(Build.SourcesDirectory)/hello-word/'

stages:
- stage: Build
  displayName: Build and Publish Project
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: NodeTool@0
      displayName: 'Use Node 16.x LTS'
      inputs:
        versionSpec: '16.x'
    - task: Npm@1
      displayName: 'npm install @angular/cli@13.3.0'
      inputs:
        command: 'custom'
        customCommand: 'install @angular/cli@13.3.0 -g'
        workingDir: $(workingDirectory)
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        verbose: false
        command: install
        workingDir: $(workingDirectory)
    - task: Npm@1
      displayName: 'npm run build'
      inputs:
        verbose: false
        command: custom
        customCommand: run build --prod
        workingDir: $(workingDirectory)
    - task: AzureStaticWebApp@0
      displayName: Deploy in Azure Static Web App
      inputs:
        app_location: '/'
        output_location: ''
        skip_app_build: true
        workingDirectory: '$(workingDirectory)/dist/hello-world'
        azure_static_web_apps_api_token: $(deployment_token)